### ISSUE TITLE
Swift 5.6 Release?

### ISSUE THREAD

**Issue by nikitaame** [CombineCommunity/CombineExt#123]
Will there be a Swift 5.6 compatible release?

**Comment by danhalliday** [comment]
I’m using CombineExt with Swift 5.6 and all looks to be working! Is there something in particular you’re coming up against?

**Comment by nikitaame** [comment]
Was seeing a `Module compiled with Swift X cannot be imported by the Swift Y compiler` type message.

**Comment by freak4pc** [comment]
> Was seeing a `Module compiled with Swift X cannot be imported by the Swift Y compiler` type message.

I imagine you're using Carthage

**Comment by nikitaame** [comment]
@freak4pc nope, SPM!

**Comment by freak4pc** [comment]
> @freak4pc nope, SPM!

In that case it just sounds like a bad local cache. SPM should build from source, there is nothing "specific to 5.6" going on here. 

Closing. Let me know if you have other questions s
