### ISSUE TITLE
‘Replace’ Operator

### ISSUE THREAD

**Issue by danhalliday** [CombineCommunity/CombineExt#125]
Just came across this library. Many thanks for all the contributions it’s super useful!

I’m looking for info on what I’ve always called 'replace'. I have some version of the following in a bunch of projects:

```swift
extension Publisher {
    public func replace<T>(_ transform: @autoclosure @escaping () -> T) -> Publishers.Map<Self, T> {
        map { _ in transform() }
    }
}
```

All it is is a `map` where you don’t have to manually ignore the transform argument. But it cleans things up just a little in a  bunch of places, especially with the `@autoclosure` allowing a constant value to be passed in. Eg:

```swift
// Before

Navigation.Show
    .subscribe()
    .filter(\.destination.isModal)
    .map { _ in Sidebar.Hide(delay: 0.25) }

// After

Navigation.Show
    .subscribe()
    .filter(\.destination.isModal)
    .replace(Sidebar.Hide(delay: 0.25))
```

Is there any precedent for this in other reactive libraries? Or is it pointless sugar?

**Comment by freak4pc** [comment]
Hey @danhalliday, thanks for the suggestion :) 
In RxSwiftExt, for example, we usually call this `map<T>(to: T)`, and then you can do `map(to: Sidebar.Hide(delay: 0.25))`. Is this what you're looking for, more or less?

**Comment by danhalliday** [comment]
Oh I totally overlooked that one. That’s great It’s a nicer spelling and good to know if I’m using it that others may be familiar with it from RX.

Is this project open to PRs for new operator suggestions? I don’t know whether others would find a trivial one like this useful but for me it’s quite nice for the Redux action use cases like the above.

**Comment by freak4pc** [comment]
Sure, happy to take a PR for this.
It’s trivial but also a good QOL operator IMO.

Thanks!
