### ISSUE TITLE
⚗️ Introducing `reduce(into:)`

### ISSUE THREAD

**Issue by jdisho** [CombineCommunity/CombineExt#13]
Hi folks 👋

Since Swift Stdlib supports [`reduce(_:_:)`](https://developer.apple.com/documentation/swift/array/2298686-reduce#declarations) and [`reduce(into:_:)`](https://developer.apple.com/documentation/swift/array/3126956-reduce), how about introducing the Combine version of `reduce(into:_:)` into this library? 

- Just for convenience, it can be a wrapper around `reduce(_:_:)`, like the following: 

```swift 
public extension Publisher {
    func reduce<Result>(into initialResult: Result, _ nextPartialResult: @escaping (inout Result, Output) -> Void) -> Publishers.Reduce<Self, Result> {
        reduce(initialResult) { initial, nextPartial -> Result in
            var result = initial
            nextPartialResult(&result, nextPartial)
            return result
        }
    }
}
```

- Another option would be to create a new operator, e.g: `Publishers.ReduceInto<Upstream, Output>`. 

Which one do you think makes more sense? 😊

Personally, since the wrapper does not mimic `reduce(into:_:)` implementation from Stdlib, because it is just a wrapper around `reduce(_:_:)`, I'm leaning towards creating a new operator.

**Comment by jdisho** [comment]
Similar approach can be applied to `scan(_:_:)` too.

**Comment by freak4pc** [comment]
This is a great idea, I'm always bummed and used to having this from RxSwift :) 

I don't think you can achieve this without a custom publisher (because you won't get by-reference semantics)

**Comment by jdisho** [comment]
If I understood correctly... 🐒
You are saying that wrapping `reduce(_:_:)` is the only way?

**Comment by freak4pc** [comment]
I actually realized you're probably looking for `scan(into:)` - 
`reduce` only works on the finished publisher so being by-reference isn't too useful, right? 

In the `scan` case - yes you'd need to create a custom publisher that pass es the `inout` seed instead of returning a new one every time.

**Comment by freak4pc** [comment]
@jdisho Should we make a decision on this?

**Comment by joewalsh** [comment]
I went looking for `reduce(into:)` and the implementation I landed on was to `collect()` and then call `reduce(into:)` on the resulting array. Does that make sense for this feature request as well?

```swift
public extension Publisher {
    func reduce<Result>(into initialResult: Result, _ nextPartialResult: @escaping (inout Result, Output) -> Void) -> AnyPublisher<Result, Failure> {
        collect()
            .map {
                $0.reduce(into: initialResult, nextPartialResult)
            }
            .eraseToAnyPublisher()
    }
}
```

**Comment by freak4pc** [comment]
Hey @joewalsh, As I noted for @jdisho - `reduce(into:)` isn't too useful since the reference semantics provide little value once the entire publisher is already done. But yes, that implementation seems correct.

What would be really good to add is `scan(into:)`

**Comment by joewalsh** [comment]
@freak4pc thanks for the feedback! I made initial attempts at [scan(into:)](https://github.com/joewalsh/CombineExt/blob/AwaitAll/Sources/Operators/ScanInto.swift) and [reduce(into:)](https://github.com/joewalsh/CombineExt/blob/AwaitAll/Sources/Operators/ReduceInto.swift) as custom publishers. Am I understanding it correctly that `scan(into:)` would emit the next combined result whenever the upstream emits and `reduce(into:)` would only emit when the upstream finishes?

**Comment by freak4pc** [comment]
Right, while not creating a new copy every time, but using the same seed.

I actually realized, that I think this works?

```swift
public extension Publisher {
    func scan<T>(into initialResult: T, _ nextPartialResult: @escaping (inout T, Output) -> Void) -> Publishers.Map<Self, T> {
        var seed = initialResult
        return map { current -> T in
            nextPartialResult(&seed, current)
            return seed
        }
    }
}
```

Usage:
![image](https://user-images.githubusercontent.com/605076/90538809-b9aa4600-e187-11ea-8600-448267cd4f27.png)

**Comment by joewalsh** [comment]
Looks like it! Much simpler too. Would it need protection against concurrent access to `seed`?

**Comment by freak4pc** [comment]
That's a good question, I'm not entirely sure but it might worth adding a `NSRecursiveLock` around it.
