### ISSUE TITLE
Issues with the xcodeproj file

### ISSUE THREAD

**Issue by jasdeepsaini** [CombineCommunity/CombineExt#134]
I have a [PR](https://github.com/CombineCommunity/CombineExt/pull/133) that fixes several issues with CombineEXT.xcodeproj. I forked the project to investigate a bug with `CurrentValueRelay` and could not run tests until I made these changes. Tests do run fine from the command line.

Fixes to get the project and tests to build:
- Deleted the missing `MapTo` and `MapToTests` files.
- Changed the deployment target to iOS 13 to match the minimum target of the Package file.
- Updated the CombineSchedulers package to 0.5.3 to match the Package file.
- The Package.resolved file automatically got updated to v2 since I am using Xcode 13.

Project cleanup
- Deleted the missing `Carthage` and `CHANGELOG.MD` files.

Missing library and test files added to the project:
- `MapToValue.swift`
- `MapToValueTests.swift`
- `MapToResult.swift`
- `MapToResultTests.swift`
- `Enumerated.swift`
- `EnumeratedTests.swift`

**Comment by freak4pc** [comment]
Hey, there's no need to open an issue in addition to the PR. Let's keep a discussion there.
Thanks.
