### ISSUE TITLE
Is there Combine equivalent to RxSwiftExt apply operator ?

### ISSUE THREAD

**Issue by evyasafm** [CombineCommunity/CombineExt#160]
https://github.com/RxSwiftCommunity/RxSwiftExt#apply

**Comment by freak4pc** [comment]
To be honest, I've never used it, but it seems really simple based on the codebase, basically a mapping function:

```
public extension Publisher {
    func apply<Output: Publisher>(
        _ transform: (Self) -> Output
    ) -> Output {
        transform(self)
    }
}
```

**Comment by freak4pc** [comment]
Closing for now, feel free to reply if this didn't solve it for you.

**Comment by evyasafm** [comment]
@freak4pc great, tnx
