### ISSUE TITLE
CombineLatestMany behavior for 0 publishers

### ISSUE THREAD

**Issue by peteranny** [CombineCommunity/CombineExt#164]
Hello, I want to confirm the `CombineLatestMany` behavior for 0 publishers. Unlike:
```swift
let publishers: [Just] = [Just(1), Just(2)]
model.subscription = publishers.combineLatest().sink(receiveValue: { print($0) })
// [1, 2]
```
Zero publishers result in
```swift
let publishers: [AnyPublisher<Int, Never>] = []
model.subscription = publishers.combineLatest().sink(receiveValue: { print($0) })
// No output
```
in which I would expect to have `[]` rather than nothing. In my case, the current behavior arose a bug in my application as I expected there would always an output no matter how many publishers. I had to manually substitute `Just([])` when 0 publishers.

As noted in the CombineExt README, CombineExt was inspired by RxSwift. I just checked the behavior in RxSwift:

```swift
let observables: [Observable] = [.just(1), .just(2)]
_ = Observable.combineLatest(observables).subscribe(onNext: { print($0) })
// [1, 2]
```

and if 0 observables:
```swift
let observables: [Observable<Int>] = []
_ = Observable.combineLatest(observables).subscribe(onNext: { print($0) })
// []
```

Wonder if we would prefer aligning this case as RxSwift does?

**Comment by jasdev** [comment]
Some earlier discussion on this https://github.com/CombineCommunity/CombineExt/issues/118#issuecomment-1068410307

**Comment by peteranny** [comment]
Thank you! I searched the open issues but not the closed. I'm closing this one!
