### ISSUE TITLE
Apple privacy manifest support

### ISSUE THREAD

**Issue by haile113** [CombineCommunity/CombineExt#169]
Hi,

Apple is enforcing every app and SDK provider to provide privacy manifest in their SDK, would you please let me know is there any plan for the support?

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by Asavarkhul** [comment]
Hello there 👋

Deadline is going short notice and we are still waiting for an update regarding privacy manifest file support, could you give us an update on this part please?

Best regards,

**Comment by freak4pc** [comment]
Hey, this library does not require a privacy manifest. It does not use any of the APIs listed in Apple's instructions.
