### ISSUE TITLE
CFBundleVersion is missing for binary release 1.1.0

### ISSUE THREAD

**Issue by nikita-leonov** [CombineCommunity/CombineExt#34]
`CFBundleVersion` is a required field according to [documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion) for the AppStore release.
> This key is required by the App Store and is used throughout the system to identify the version of the build. For macOS apps, increment the build version before you distribute a build.

As of now release to App Store with an CombineExt failing with a following error:

> ERROR [2020-05-15 17:02:14.73]: [31mERROR ITMS-90056: "This bundle Payload/Confluence.app/Frameworks/CombineExt.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

**Comment by freak4pc** [comment]
Hey @nikita-leonov, good catch!
Just want to confirm, are you a Carthage user? I believe SPM and CocoaPods add their own Info.plist.

**Comment by nikita-leonov** [comment]
Yes, we are integrating CombineExt with Carthage.

**Comment by freak4pc** [comment]
Ney @nikita-leonov - I tried adding it into 1.2.0, can you try and let me know? Thanks !

**Comment by danielob** [comment]
@freak4pc The compiled binary `1.2.0` still missing `CFBundleVersion` in the `info.plist`. I posted a PR to add target flag that is required for the info plist to update that.
https://github.com/CombineCommunity/CombineExt/pull/36

**Comment by freak4pc** [comment]
Did you check 1.3.0 @danielob ?

**Comment by nikita-leonov** [comment]
> Did you check 1.3.0 @danielob ?

We did, and it is also missing Bundle Version, as Current Project Version is not set, as result Bundle Version was not generated.

**Comment by freak4pc** [comment]
Hey @nikita-leonov - I uploaded a new binary on top of the 1.2.0 release which should have the release in CFBundleVersion and short version as well. Can you please try? You might need to clear your Carthage cache: `rm -rf ~/Library/Caches/carthage`

**Comment by freak4pc** [comment]
Sorry to bug again, I'd just really want to make sure this is working finally :) 
Mind confirming if you have a few moments @nikita-leonov, @danielob ?

**Comment by nikita-leonov** [comment]
@freak4pc sorry for a delay, me
and Daniel got a little bit swamped with a release. We will confirm tomorrow. Thanks!

**Comment by nikita-leonov** [comment]
@freak4pc the binary scenario works thanks! The build from source now completely broken. It is quite unfortunate that in our case we may use both scenarios so may need still to keep a private fork a some time. 
Btw just our of curiosity, is cocoa pods scenario works fine without having a project file in place? It was a while since I used it.

**Comment by freak4pc** [comment]
@nikita-leonov Carthage is the only dependency manager which depends on a project. 

TBH I don't mind checking that in. I'll add back the project.

**Comment by freak4pc** [comment]
@nikita-leonov I force-pushed adding the project back onto the last commit. You should be good to go now, let me know if you have any other issues.
