### ISSUE TITLE
Possible memory leak in CombineExt

### ISSUE THREAD

**Issue by yoavschwartz** [CombineCommunity/CombineExt#42]
Hi, I am not sure if this is a bug with Combine or CombineExt but I have run a cross a super weird case.
the following code:
```
        Timer.publish(every: 1, on: .main, in: .default)
            .autoconnect()
            .map { _ -> AnyPublisher<Bool, Never> in
                return AnyPublisher<Bool, Error> { subscriber in
                    subscriber.send(true)
                    subscriber.send(completion: .finished)
                    return AnyCancellable {}
                }
                .replaceError(with: false)
//                .catch { _ in Just(false) }
//                .assertNoFailure()
                .eraseToAnyPublisher()
        }
        .switchToLatest()
        .sink { _ in }
        .store(in: &subscriptions)
    }
```
Will produce a memory leak, where every second another retain will occour, however if you replace `replaceError` with either `catch` or `assertNoFailure` everything works fine.
I am using the latest version of xcode and iOS, and I could reproduce both in simulator and on a real device

**Comment by freak4pc** [comment]
switchToLatest is broken under 13.3 or 13.4, this isn’t related to CombineExt. See here: https://forums.swift.org/t/confused-about-behaviour-of-switchtolatest-in-combine/29914/39

**Comment by yoavschwartz** [comment]
I am aware it is broken on 13.3, and should have been fixed on 13.4, however this is hapenning on 13.5.1

**Comment by freak4pc** [comment]
Try a different publisher instead of create, would be easier to isolate the issue

**Comment by yoavschwartz** [comment]
```
        let url = URL(string: "https://example.com")!

        Timer.publish(every: 2, on: .main, in: .default)
            .autoconnect()
            .map { _ -> AnyPublisher<Bool, Never> in
                return URLSession.shared
                .dataTaskPublisher(for: url)
                .print("task")
                    .map { _ in true }
                    .replaceError(with: false)
                    //                .catch { _ in Just(false) }
                    //                .assertNoFailure()
                    .eraseToAnyPublisher()
        }
        .switchToLatest()
        .sink { _ in }
        .store(in: &subscriptions)
```

Produces the same result. I guess that means this is not the right place for it, but could it be a Combine bug?

**Comment by freak4pc** [comment]
It sure seems like it. Are you in Xcode 11.5 in that case ? I’d try going to iOS 13.4 and see if it occurs there as well. Could be a new regression.

**Comment by yoavschwartz** [comment]
I am in Xcode 11.5, and iOS 13.5.x on both simulator and device. Seems to be specific to replaceError. I also managed to "work around" by doing `.prefix(1)` which then sends the cancel event before the finish event.
