### ISSUE TITLE
Using Collection publishers on publishers of disparate Output types

### ISSUE THREAD

**Issue by AndrewSB** [CombineCommunity/CombineExt#44]
I'm having issues constructing an invocation to Collection.combineLatest when my Publishers have different types. An example:

```swift 
@Published var s: String
@Published var i: Int

[s, i].combineLatest -> ERROR: Heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional
```

Since the array can't be constrained to `[Publisher]` - `Protocol 'Publisher' can only be used as a generic constraint because it has Self or associated type requirements`, none of the Collection publisher functions are available. Is there a workaround for issues like this? Or is it only expected to use the Collection publishers on publisher of the same output type?

**Comment by freak4pc** [comment]
Arrays are strict around a single generic type. You can have an array of many genetics (as of now, at least) so there’s no way in the compiler to express what you want.

What people usually do (and what Apple does) is create overloads up to some specific arity, I believe up to 4. In RxSwift for example it goes up to 8. Regardless it’s not arbitrary but limited.

**Comment by AndrewSB** [comment]
Dang, so I guess I need a `CombineLatest5`. Thanks for all of your work @freak4pc

**Comment by AndrewSB** [comment]
actually ended up doing a `Publisher.CombineLatest(Publishers.CombineLatest4, myPublisher)`

**Comment by freak4pc** [comment]
@AndrewSB Yup, that would be the way to go without a bigger option. You can wrap it like this

```swift
extension Publisher {
    public func combineLatest<A: Publisher, B: Publisher, C: Publisher, D: Publisher>(
        _ publisher1: A,
        _ publisher2: B,
        _ publisher3: C,
        _ publisher4: D
    ) -> AnyPublisher<(Self.Output, A.Output, B.Output, C.Output, D.Output), Failure> where Self.Failure == A.Failure, A.Failure == B.Failure, B.Failure == C.Failure, C.Failure == D.Failure {
        combineLatest(Publishers.CombineLatest4(publisher1,
                                                publisher2,
                                                publisher3,
                                                publisher4)) { one, four in
            (one, four.0, four.1, four.2, four.3)
        }.eraseToAnyPublisher()
    }
}

// use: first.combineLatest(second, third, fourth, fifth)
```
