### ISSUE TITLE
SinglePublisher

### ISSUE THREAD

**Issue by groue** [CombineCommunity/CombineExt#45]
Hello,

I'm currently using a `SinglePublisher` subprotocol of `Publisher`, which comes with the guarantee that a publisher publishes exactly one element, or an error.

https://gist.github.com/groue/6226a6a2cde190f819b37aa58ff9dd36

Quoting the doc:

```
/// The protocol for "single publishers", which publish exactly one element, or
/// an error.
///
/// `Just`, `Future` and `URLSession.DataTaskPublisher` are examples of
/// publishers that conform to `SinglePublisher`.
///
/// Conversely, `Publishers.Sequence` is not a single publisher, because not all
/// sequences contain a single element.
///
/// # SinglePublisher Benefits
///
/// Once you have a publisher that conforms to `SinglePublisher`, you have
/// access to two desirable tools:
///
/// - A `AnySinglePublisher` type that hides details you don’t want to expose
///   across API boundaries. For example, the user of the publisher below knows
///   that it publishes exactly one `String`, no more, no less:
///
///         func namePublisher() -> AnySinglePublisher<String, Error>
///
///   You build an `AnySinglePublisher` with the
///   `eraseToAnySinglePublisher()` method:
///
///         mySinglePublisher.eraseToAnySinglePublisher()
///
/// - A `sinkSingle(receiveResult:)` method that simplifies handling of single
///   publisher results:
///
///         namePublisher().sinkSingle { result in
///             switch result {
///                 case let .success(name): print(name)
///                 case let .failure(error): print(error)
///             }
///         }
```

I was wondering if you would be interested in including such a feature in CombineExt.

**Comment by freak4pc** [comment]
Hey! I definitely would :) 

I actually started doing some work on Single and Completable in [a separate branch](https://github.com/CombineCommunity/CombineExt/tree/traits) but I kinda left it alone, I need to get back to it.

I don't think it needs a protocol abstraction, seems like a regular concrete type could provide a strong enough guarantee. WDYT? @groue

**Comment by groue** [comment]
Thanks @freak4pc! I do not expect the *design* of such feature to converge easily, so I stay very humble.

> I don't think it needs a protocol abstraction, seems like a regular concrete type could provide a strong enough guarantee. 

This was the RxSwift way.

But all built-in Combine operators such `map`, `flatMap`, `retry`, etc. return a *specific* type instead of a type-erased publisher.

**This means we don't need to reimplement all flow operators as RxSwift had to do.**

In the implementation I suggest, many Combine publishers are given a `SinglePublisher` conformance or conditional conformance (see at the end of the gist).

Consider this sample code:
```swift
func myPublisher() -> AnySinglePublisher<String, Error> {
    Just("Hello")
        .setFailureType(to: Error.self)
        .delay(for: .seconds(2), scheduler: DispatchQueue.main)
        .eraseToAnySinglePublisher()
}
```

- `Just` conforms to `SinglePublisher`.
- `setFailureType` preserves this information
- `delay` preserves this information
- so `eraseToAnySinglePublisher` is available.

In the same vein, flatMapping single publishers produces statically known single publishers, etc.

May I suggest that you take some time to evaluate the approach, maybe live with it a few days?

**Comment by freak4pc** [comment]
Actually the RxSwift way is protocol-based, there's just a conforming object. 

Sure, I'll rethink it. Regardless, if you use type-erasure, you can get the same benefits with a regular concrete type, because you can use a regular `Single` conforming to `Publisher` and just erase it after applying the operator. 

It does mean (from my understanding) that you'd have to erase to a single publisher every time you apply some operators, is that correct?

**Comment by groue** [comment]
> Regardless, if you use type-erasure, you can get the same benefits with a regular concrete type, because you can use a regular Single conforming to Publisher and just erase it after applying the operator.

Quoting Apple doc:

> Use `AnyPublisher` to wrap a publisher whose type has details you don’t want to expose across API boundaries, such as different modules.

With due compliance to the "Combine way", the `AnySinglePublisher` I suggest here has the exact same purpose, no more, no less. You named it `Single` in your branch.

`AnySinglePublisher` communicates that you'll get a publisher that publishes exactly one element or one error:

```swift
// Raw Combine: no way to tell a single foo will be published
func fooPublisher() -> AnyPublisher<Foo, Error>

// Better
func fooPublisher() -> AnySinglePublisher<Foo, Error>
```

> It does mean (from my understanding) that you'd have to erase to a single publisher every time you apply some operators, is that correct?

No.

For example, the gist comes with `sinkSingle`.

The purpose of `sinkSingle` is to help consuming single publishers:

```swift
// Raw Combine
let cancellable = somePublisher.sink(
    receiveCompletion: { completion in
        switch completion {
        case let .failure(error):
            // Handle error
        case .finished:
            break
        }
    },
    receiveValue: { value in
        // Handle success
    })

// With `SinglePublisher`
let cancellable = someSinglePublisher.sinkSingle { result in
    switch result {
    case let .failure(error):
        // Handle error
    case let .success(value):
        // Handle success
    }
}
```

`sinkSingle` helps consuming *all* single publishers, not only `AnySinglePublisher`. With a protocol, there is no need for any type erasure, as in the sample code below:

```swift
Result { ... }
    .publisher
    .flatMap { someSingleStuff($0 }
    .map(transform)
    .retry(3)
    .sinkSingle { result in
        switch result {
        case let .failure(error):
            // Handle error
        case let .success(value):
            // Handle success
        }
    }
```

Finally, yes, there are type-erasure methods. But they do not exist as a convenience for the library. They exist *for the user*, when he decides he needs type erasure. This looked, to me, like the Combine way.

**Comment by groue** [comment]
The gist comes with a general introduction to the SinglePublisher protocol, that I copy below: https://gist.github.com/groue/6226a6a2cde190f819b37aa58ff9dd36

Most single publishers are what is called "Compiler-checked single publishers" in this introduction. That's why type erasure is not frequent (unless the user *wants* to return an `AnySinglePublisher`).

---

The protocol for "single publishers", which publish exactly one element, or an error.

`Just`, `Future` and `URLSession.DataTaskPublisher` are examples of publishers that conform to `SinglePublisher`.

Conversely, `Publishers.Sequence` is not a single publisher, because not all sequences contain a single element.

### SinglePublisher Benefits

Once you have a publisher that conforms to `SinglePublisher`, you have access to two desirable tools:

- A `AnySinglePublisher` type that hides details you don’t want to expose across API boundaries. For example, the user of the publisher below knows that it publishes exactly one `String`, no more, no less:

    ```swift
    func namePublisher() -> AnySinglePublisher<String, Error>
    ```

    You build an `AnySinglePublisher` with the `eraseToAnySinglePublisher()` method:

    ```swift
    mySinglePublisher.eraseToAnySinglePublisher()
    ```

- A `sinkSingle(receiveResult:)` method that simplifies handling of single publisher results:

    ```swift
    namePublisher().sinkSingle { result in
        switch result {
        case let .success(name): print(name)
        case let .failure(error): print(error)
        }
    }
    ```

### Building Single Publishers

In order to benefit from the `SinglePublisher` protocol, you need a concrete publisher that conforms to this protocol.

There are a few ways to get such a single publisher:

- **Compiler-checked single publishers** are publishers that conform to the `SinglePublisher` protocol. This is the case of `Just` and `Fail`, for example. Some publishers conditionally conform to `SinglePublisher`, such as `Publishers.Map`, when the upstream publisher is a single publisher.

    When you define a publisher type that publishes exactly one element, or an error, you can turn it into a single publisher with an extension:
    
    ```swift
    struct MySinglePublisher: Publisher { ... }
    extension MySinglePublisher: SinglePublisher { }
    ```

- **Runtime-checked single publishers** are publishers that conform to the `SinglePublisher` protocol by checking, at runtime, that an upstream publisher publishes exactly one element, or an error.

    You build a checked single publisher with one of those methods:

    - `Publisher.checkSingle()` returns a single publisher that fails with a `SingleError` if the upstream publisher does not publish exactly one element, or an error.

    - `Publisher.assertSingle()` returns a single publisher that raises a fatal error if the upstream publisher does not publish exactly one element, or an error.

- **Unchecked single publishers**: you should only build such a single publisher when you are sure that the `SinglePublisher` contract is honored by the upstream publisher.

    For example:

    ```swift
    // CORRECT: those publish exactly one element, or an error.
    [1].publisher.uncheckedSingle()
    [1, 2].publisher.prefix(1).uncheckedSingle()
    
    // WRONG: does not publish any element
    Empty().uncheckedSingle()
    
    // WRONG: publishes more than one element
    [1, 2].publisher.uncheckedSingle()
    
    // WRONG: does not publish exactly one element, or an error
    Just(1).append(Fail(error))
    
    // WARNING: may not publish exactly one element, or an error
    someSubject.prefix(1).uncheckedSingle()
    ```

    The consequences of using `uncheckedSingle()` on a publisher that does not publish exactly one element, or an error, are undefined.

### Basic Single Publishers

`AnySinglePublisher` comes with factory methods that build basic single publishers:

```swift
// Immediately publishes one value, and then completes.
AnySinglePublisher.just(value)
   
// Immediately fails with the given error.
AnySinglePublisher.fail(error)
   
// Never publishes any value, never completes.
AnySinglePublisher.never()
```

**Comment by freak4pc** [comment]
Realize it has been a few months, i always come back to this one and having a hard time circling around and feeling at peace with the kind of complexity this introduces. I would also prefer using the regular sink and not specially-named subscribers for this sort of things. Regardless, I have a few days off soon and will try to find time to do a proper review of the code.

**Comment by groue** [comment]
Thanks @freak4pc. The ideas in this pull request are living in https://github.com/groue/CombineTraits. Since this PR, the "maybe" trait was introduced, doc has been enhanced, and general robustness was improved as well (since I've been using it in more apps).

**Comment by groue** [comment]
Also, thanks for challenging the design. Here are some answers:

> [...] the kind of complexity this introduces.

The runtime complexity is basically zero: `SinglePublisher` is a marker protocol that comes with no runtime at all, but makes the `eraseToAnySinglePublisher()` method available. This is the method that makes it possible to guarantee publisher characteristics at API boundaries, the fundamental goal of the lib (see https://github.com/groue/CombineTraits/blob/main/Documentation/Single.md#anysinglepublisher).

The lib comes with a lot of [ready-made conformances](https://github.com/groue/CombineTraits/blob/main/Sources/CombineTraits/Combine%2BSinglePublisher.swift) for built-in Combine publishers.

The lib executes some code when one explicitly asks for a *checked* publisher (the runtime makes sure the publisher honors the trait's contract, as RxSwift `asSingle()`), or creates a single publisher from a closure (as CombineExt `AnyPublisher.create`).

> I would also prefer using the regular sink and not specially-named subscribers for this sort of things.

Those match the specialized RxSwift `subscribe` methods. And I wrote a rationale: https://github.com/groue/CombineTraits/blob/main/Documentation/Single.md#sinksinglereceive

**Comment by groue** [comment]
Small update: a new trait was added alongside Single and Maybe: [Immediate publishers](https://github.com/groue/CombineTraits/blob/main/Documentation/Immediate.md). Those publish a value, or fail, right on subscription. I expect they'll help apps enforce at the compiler level that some scenarios must not involve any latency or delay.

**Comment by freak4pc** [comment]
Thanks! Is that just some trait that encapsulated Fail and Just?

**Comment by groue** [comment]
> Thanks! Is that just some trait that encapsulated Fail and Just?

Oops, I did not write clearly! They can publish any number of values, but they must publish the first one synchronously, and can't complete empty. I'm tired at wondering if a view controller should plan a design for a waiting state or not ;-)

**Comment by freak4pc** [comment]
Sorry for taking so long to think this through, it's been a crazy few months :) 

First of all I really liked the way you organized them and built them, but that kinda makes me feel it should remain as an independent project for those who are interested in specific traits. 

I would really love it if you'd want to put your project in the Community organization, but that's up to you of course :)

**Comment by groue** [comment]
All right, @freak4pc, CombineTraits will remain independent! There's no point bringing it into the Community, since you will tackle this topic one day or another, and it would not be desirable that there exists two conflicting flavors of traits under the Community umbrella.

**Comment by freak4pc** [comment]
Thanks! I do understand why you think so @groue, but that's not really how I see things.
Your project made me realize it doesn't make sense for CombineExt to have these traits. It does feel better at a separate project. 

There's no reason for community to pursue this if there's a good option already available. (Preferably an option inside Community if you would want to, but not only)
