### ISSUE TITLE
replaceEmpty/replaceNil/replaceError with publisher parameter

### ISSUE THREAD

**Issue by yhkaplan** [CombineCommunity/CombineExt#46]
I was looking at for something like RxSwift's `ifEmpty(switchTo:)`, and there appeared to be a solution in
[rxswift-to-combine-cheatsheet](https://github.com/CombineCommunity/rxswift-to-combine-cheatsheet), but current versions of Combine do not offer `replaceEmpty(with  publisher: Publisher)`. I'm thinking something like the below would work, but what do you think? If it's okay, I'll go ahead and make a pull request.

```swift
public extension Publisher where Output: Collection {
    func replaceEmpty(with publisher: AnyPublisher<Output, Failure>) -> AnyPublisher<Output, Failure> {
        flatMap { (output: Output) -> AnyPublisher<Output, Failure> in
            if output.isEmpty { return publisher }
            return Just(output)
                .setFailureType(to: Failure.self)
                .eraseToAnyPublisher()
        }
        .eraseToAnyPublisher()
    }
}
```

**Comment by freak4pc** [comment]
Hey @yhkaplan, I think you've misunderstood how `ifEmpty(switchTo:)` works.

It isn't meant to work on empty/non-empty collections, but on empty Observables. 

That means, `a.ifEmpty(switchTo: b)` will switch into the second observable if `a` completed without emitting anything, see `DefaultIfEmpty` in ReactiveX: http://reactivex.io/documentation/operators/defaultifempty.html

It should be easy enough to make this operator, but your implementation is of something else :)
