### ISSUE TITLE
Add FilterMany

### ISSUE THREAD

**Issue by kevinrenskers** [CombineCommunity/CombineExt#58]
Just like `MapMany`; it's pretty common for me to have a publisher of an array, and then I want to filter the items inside the array. So now I have to combine a filter inside a map, and a `filterMany` would be a pretty nice convenience.

**Comment by freak4pc** [comment]
Happy to accept it if you put together a quick PR with some tests :)

**Comment by HugoSay** [comment]
I added a first implementation for the filterMany operator if you want to check it 🙂

**Comment by kevinrenskers** [comment]
Oh I was just about to create a branch for it to dig in. Thanks!
