### ISSUE TITLE
Thread-safety of ReplaySubject?

### ISSUE THREAD

**Issue by mattmassicotte** [CombineCommunity/CombineExt#64]
Hello! I'd just like to preface this issue by saying that I'm quite new to both Combine and reactive programming in general. So, it is possible that this isn't actually an issue.

I've put together a test that reliably crashes in `ReplaySubject`. Peeking in the code, it looks like there isn't any kind of synchronization, so this doesn't surprise me too much. Here's the example, which simulates an expensive, on-time initialization process, which is then shared by many potential downstream consumers.

```swift
let initPublisher = Deferred {
    Future<Int, Error> { (promise) in
        print("init starting")
        sleep(1)
        print("init completed")

        promise(.success(42))
    }
}
.share(replay: 1)
.subscribe(on: queue) // <- this appears necessary
.eraseToAnyPublisher()

let group = DispatchGroup()
var localCancellables = Set<AnyCancellable>()

for i in 0..<20 {
    group.enter()
    DispatchQueue.global().async {
        print("running \(i)")

        initPublisher
            .map { (value) -> Int in
                print("beginning sleep \(i)")
                usleep(500)
                print("ending sleep \(i)")
                return value
            }
            .sink { (completion) in
            print("completion \(i): \(completion)")

            group.leave()
        } receiveValue: { (result) in
            print("result \(i): \(result)")
        }
        .store(in: &localCancellables)
    }
}

group.wait()
print("completed all")
```

As indicated in the code, it looks like the addition of a `subscribe(on:)` added the necessary synchronization. My question is, is that expected, or should `ReplaySubject` be thread-safe?

**Comment by freak4pc** [comment]
Replace it with a current value subject. If that one's thread safe, we should align.
