### ISSUE TITLE
Collection.combineLatest empty collection behavior.

### ISSUE THREAD

**Issue by palle-k** [CombineCommunity/CombineExt#65]
Currently, when calling `combineLatest()` on an empty collection of publishers, an empty publisher is emitted that completes immediately. 

Instead, wouldn't it make sense to publish just an empty array instead (`Just([])`)?

`combineLatest()` emits the first output when all source publishers have emitted at least one output.
A for-all operator on an empty sequence would return true, which would mean that the `combineLatest` operator would have to immediately return `[]` when given an empty collection.

**Comment by freak4pc** [comment]
Not really. It also doesn't correlate with combineLatest behavior.
It doesn't make sense that something that combines different publishers would emit _anything_ if none of its members do. 

I'm not sure what's a for-all operator or what's the specific correlation to combineLatest's behavior

**Comment by palle-k** [comment]
With the for-all operator I mean the universal quantifier: https://en.wikipedia.org/wiki/Universal_quantification#The_empty_set

**Comment by freak4pc** [comment]
Combine / Rx operators don't necessarily correlate with set theory, nor should it. Regardless, this behavior doesn't make sense in case of publishers / streams based on other implementations and known behaviors of this operaor.
