### ISSUE TITLE
Add debug

### ISSUE THREAD

**Issue by Nickersoft** [CombineCommunity/CombineExt#67]
For me, one of the most useful operators from RxSwift has been `debug()` to quickly log the stream of items passing through an Observable. A while back, I tried my hand at implementing the operator myself in Combine but got a bit lost in terms of writing the Sink and working with the Combine utility classes. I'd be happy to help assist in adding it to this library with a bit of guidance.

**Comment by jasdev** [comment]
[`Publisher.print(_:to:)`](https://developer.apple.com/documentation/combine/publisher/print(_:to:)) might be what you’re looking for. 🎉

**Comment by Nickersoft** [comment]
Wow absolutely – had no idea this was built in. Thanks 👍
