### ISSUE TITLE
[Not really an issue, but] Is release 1.3.0 planed ?

### ISSUE THREAD

**Issue by Khronoss** [CombineCommunity/CombineExt#71]
Hi,

I'm still using Cocoapods, and the latest version is 1.2.0. I see there has been some operators added since (especialy the `toggle` operator, that I was looking for)
I don't know how SPM handles version updates, but Cocoapods needs tags for tracking the versions, so my question is:
Is there any plan to create an update that includes all new operators or are you waiting to have enough or something?

**Comment by freak4pc** [comment]
Hey @Khronoss
You can simply link directly to the `main` branch or even to the specific `commit` SHA in your Podfile.

I don't have an ETA on 1.3.0 but it should be soon.

**Comment by Khronoss** [comment]
Ah, right 👍 
Thank you @freak4pc
