### ISSUE TITLE
[Request] Change combineLatest() count == 0 to publish []

### ISSUE THREAD

**Issue by Ivorforce** [CombineCommunity/CombineExt#75]
If you have an array of unknown size, you expect it to be published once all elements are there.

If you don't have any elements, I'd argue you expect it to publish immediately with an empty array - since that's the natural value it would assume. Otherwise, other subscribers might wait forever on its output.

[Sample implementation](https://github.com/CombineCommunity/CombineExt/blob/main/Sources/Operators/CombineLatestMany.swift#L58):

`Just([]).mapError { $0 as! Element.Failure }.eraseToAnyPublisher()`

**Comment by freak4pc** [comment]
Hey, I'm sorry but this really doesn't make sense - 
Sounds like a logical check you might want to do on your end.

A Combine Latest with no items means there's nothing to combine which means you'll never get an emission. This is also the logic in other Reactive standards.

**Comment by Ivorforce** [comment]
If it is I recognise the standard and must close this issue.

Unfortunately, in all my use-cases this was against intention and rather counter-productive behaviour. I will make do with a custom implementation.
