### ISSUE TITLE
Result of zip() on empty Collection is Empty() instead of Just([])

### ISSUE THREAD

**Issue by RustamG** [CombineCommunity/CombineExt#84]
Thanks for your efforts on this set of useful features.

There's one thing that IMO should work slightly different. Although it would be a breaking change, I still wanted to bring attention to it.

The `Collection.zip()` operator returns `Empty` publisher in case the collection is empty ([source](https://github.com/CombineCommunity/CombineExt/blob/main/Sources/Operators/ZipMany.swift#L54)). It means that the downstream methods like `map`, `flatMap`, etc. will not be called. And the `receiveValue` closure on `sink()` will not be called as well. My expectation is that those methods should still be called with an empty array passed. See the following example:

```swift
var cancelBag = Set<AnyCancellable>()
let publishers: [AnyPublisher<Int, Never>] = [
//    Just(1).eraseToAnyPublisher(),
//    Just(2).eraseToAnyPublisher()
]
publishers.zip()
    .map { results -> Int in
        // return the number of results. It could be a number of loaded items, etc.
        print("Map results")
        return results.count // will not be called :(
    }
    .sink { results in
        print("Got \(results)") // will not be called :(
    }
    .store(in: &cancelBag)
```

So, I'd changed 
```swift
case 0:
    return Empty().eraseToAnyPublisher()
``` 
to 
```swift
case 0:
    return Just([]).setFailureType(to: Element.Failure.self).eraseToAnyPublisher()
```
[here](https://github.com/CombineCommunity/CombineExt/blob/main/Sources/Operators/ZipMany.swift#L53-L54)

Please let me know your thoughts.

**Comment by freak4pc** [comment]
Thanks for opening this discussion @RustamG. 

Unfortunately I believe the behavior you're suggesting is counter-intuitive. 
An array of no publishers isn't the same as a publisher of an empty array. The former is an empty stream and the later is a stream with a single value (`[]`).

It would be extremely confusing having an array that has no publishers (meaning no value) and the result of that being a single value being emitted (an empty array). Perhaps you have some business logic that depends on this, but the current behavior is the right one - and it's also in-line with how Reactive Extensions / RxSwift does this.

**Comment by RustamG** [comment]
Thanks @freak4pc. It totally makes sense. 👍
