### ISSUE TITLE
Add "catchToOutput" operator

### ISSUE THREAD

**Issue by klundberg** [CombineCommunity/CombineExt#89]
In many places in my codebase, I find myself transforming an error value into a specific kind of output value, like this:

```swift
somePublisher.catch({ error in Just(someValueFromError(error)) })
```

I'd love to be able to have some operator that makes this a little nicer to use that omits needing to worry about combining `catch` and `Just` in this way, something like this perhaps:

```swift
somePublisher.catchToOutput({ someValueFromError($0) })
// also can be used without a closure:
somePublisher.catchToOutput(someValueFromError)
```

The name could be different, I can see perhaps naming such an operator as `mapErrorToOutput` or `catchAsOutput` or something as well. Is this something CombineExt would find as a worthwhile addition?

**Comment by freak4pc** [comment]
Hey! 
Isn't this just replaceError(with:)?

**Comment by klundberg** [comment]
It's not the same, since replaceError(with:) will replace the error with a constant value. I want to be able to create a new value using the error i'm given, which is the difference. Does that sound useful to add?

**Comment by freak4pc** [comment]
Ah, gotya. Read it from my phone, sorry for the misunderstanding :) 

I can see it useful for a specific codebase that has many of these use-cases, but to be honest, all it's saving is a call to `Just`.

e.g. 
```swift
catch { Just(func($0)) } 
```

vs

```swift
catchToOutput { func($0) }
```

the latter is actually longer because of the method name. I'm not sure if it provides enough value for this framework :)

**Comment by klundberg** [comment]
Totally fair! I remember looking for an operator that does this for a bit before figuring out I can catch with Just, but I can see that it might be niche and not much in savings otherwise 🙂
