### ISSUE TITLE
Crash in iOS 13.1 & 14.1 when use withLatestFrom method

### ISSUE THREAD

**Issue by spirit-jsb** [CombineCommunity/CombineExt#94]
when i use withLatestFrom method it will crash app.

could some one help me?

```text
Fatal error: Unexpected state: received completion but do not have subscription: file Combine/Catch.swift, line 279
2021-07-08 18:11:19.869633+0800 Lit Live[31201:239977] Fatal error: Unexpected state: received completion but do not have subscription: file Combine/Catch.swift, line 279
```

<img width="1385" alt="截屏2021-07-08 18 13 09" src="https://user-images.githubusercontent.com/17959670/124904999-289ac280-e018-11eb-90f2-7dfe81da901e.png">
<img width="1421" alt="截屏2021-07-08 18 13 23" src="https://user-images.githubusercontent.com/17959670/124905025-305a6700-e018-11eb-9dd5-42442114f7e3.png">

**Comment by spirit-jsb** [comment]
withLatestFrom method receive a optional @Published parameter

**Comment by spirit-jsb** [comment]
mu，i don't know why buffer(:_) method value is nil...

**Comment by freak4pc** [comment]
There's a new implementation in 1.5.0, can you try it?

**Comment by spirit-jsb** [comment]
it's work! THX
